### ISSUE TITLE
不支持python3.5

### ISSUE THREAD

**Issue by suhli** [xxwsL/poke_auto_joy#1]
自己修改了个[版本](https://github.com/suhli/poke_auto_joy/tree/ubuntu16.04+python3.5)..可以的话开个分支我提个pr?

**Comment by xxwsL** [comment]
> 自己修改了个[版本](https://github.com/suhli/poke_auto_joy/tree/ubuntu16.04+python3.5)..可以的话开个分支我提个pr?

ok，没问题，https://github.com/xxwsL/poke_auto_joy/tree/for-python3.5

我想使用qt进行包装程序，但卡在await上面，不知你可有好的建议

**Comment by suhli** [comment]
> > 自己修改了个[版本](https://github.com/suhli/poke_auto_joy/tree/ubuntu16.04+python3.5)..可以的话开个分支我提个pr?
> 
> ok，没问题，https://github.com/xxwsL/poke_auto_joy/tree/for-python3.5
> 
> 我想使用qt进行包装程序，但卡在await上面，不知你可有好的建议

qt不太熟..也许可以做成api-server的形式?然后前端怎么搭就都可以..
